### PR TITLE
Remove non-existing buttons

### PR DESCRIPTION
**Pull request by KOPRajs**
The same as https://github.com/kodi-game/game.libretro.pcsx-rearmed/pull/26, remove buttons that actually don't exist on the controllers from the button map. I've also changed the order of the controllers to match the topology.xml.

In addition, I'm offering a new icon. I've created the icon for my own usage long time ago, because I don't like some aspects of the current bug icon (mainly it is actually a Mednafen icon and also it is the same for all former Mednafen emulator modules). The new icon is not perfect, but I was unable to find anything better. It is based on the video from the RetroArch's page on Steam (https://store.steampowered.com/app/1222630/RetroArch__Beetle_PSX/).

### CODE REVIEW

**Comment by KOPRajs** [comment]
I also got one for Saturn, if you are interested:
Beetle_PSX
Beetle_Saturn

**Comment by garbear** [comment]
Love the new icons!

**Comment by garbear** [comment]
> I've also changed the order of the controllers to match the topology.xml

 This is OK, but the order in buttonmap.xml doesn't matter, only the order in topology.xml is used. For buttonmap.xml order I usually go in order of class/subclass, but like I said it doesn't really matter.

**Comment by KOPRajs** [comment]
> > I've also changed the order of the controllers to match the topology.xml
> 
> This is OK, but the order in buttonmap.xml doesn't matter, only the order in topology.xml is used. For buttonmap.xml order I usually go in order of class/subclass, but like I said it doesn't really matter.

The new order is actually of class/subclass:
```
type="RETRO_DEVICE_ANALOG" subclass="0"
type="RETRO_DEVICE_ANALOG" subclass="1"

```
These two were 1, 0 before.

**Review by garbear — APPROVED** [review]

**Comment by garbear** [comment]
Released a new version with the updated buttonmaps

**Comment by garbear** [comment]
The beetle-saturn icon looks great. Can you PR? I'm preparing a full add-on update for LibreELEC with all the new changes.

**Pull request merged**
